global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  resolution: 0.2
  rolling_window:             false
  track_unknown_space:        true
  width:                      20.0
  height:                     20.0


  plugins:
     - {name: static,                    type: "costmap_2d::StaticLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
